### ISSUE TITLE
rtmp协议解析, protocol/rtmp.go:func (v *hsBytes) createS0S1S2()

### ISSUE THREAD

**Issue by QilongZhang** [ossrs/go-oryx#26]
按照rtmp rfc文档，　应该是copy c1 time to s2.time2
但是工程实践，copy c1 time to s1.time2?, 根据官方文档，s1没有time2, 应该是zero字段吧。

**Comment by winlinvip** [comment]
貌似是有的。rtmp协议本身adobe也不遵守，所以如果你可以找一些播放器和编码器，看这些time都是怎么搞的。

**Comment by QilongZhang** [comment]
恩，　查阅了一些资料。　谢谢winlin解答。
